apiVersion: v1
kind: Pod
metadata:
  name: {{pod_name}} 
spec:
  nodeName: {{assign_specific_node}}
  containers:
  - image: {{container_image_name}}
    name: {{container_name}}
    env:
    - name: {{container_envvar_name}}
      valueFrom:
        secretKeyRef:
          name: {{secret_name1}}
          key: {{secret_key1}}
    - name: {{container_envvar_name}}
      valueFrom:
        secretKeyRef:
          name: {{secret_name_2}}
          key: {{secret_key2}}
    securityContext:
      runAsUser: 1000
      runAsGroup: 2000
      allowPrivilegeEscalation: false
  restartPolicy: Never
  imagePullSecrets:
  - name: {{secret_to_image_repo}}
