apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-agent
  template:
    metadata:
      labels:
        app: devops-agent
        version: "0.1"
    spec:
      containers:
      - name: devops-agent
        image: {{devops_agent_image_name}} 
        env:
          - name: AZP_URL
            value: {{https_azure_devops_address}}
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{secret_name}}
                key: AZP_TOKEN
          - name: AZP_POOL
            value: {{azure_devops_pool_name}}
      imagePullSecrets:
      - name: {{image_repo_secret}}
